### ISSUE TITLE
Logs from mesos/storm repo are lost

### ISSUE THREAD

**Issue by dsKarthick** [mesos/storm#102]
When I was playing around with vagrant, I noticed that we are losing the logs generated by mesos/storm repo. That is, the mesos/storm appication logs do not appear in the `nimbus.log` but logs from storm-core still appear in the `nimbus.log`.

**Comment by dsKarthick** [comment]
The bug turns out to be related to shading. When we shade `org.slf4j`, we end up shading all the classes belonging to `slf4j-api` provided by storm-core. This causes slf4j not to bind to concrete implementation provided by storm-core. Eg. org.slf4j.Logger interface in slf4j-4j becomes org.slf4j.shaded.Logger and none of the Logger in the storm jar would implement org.slf4j.shaded.Logger.

**Comment by erikdw** [comment]
#102 was fixed by #103.
