### ISSUE TITLE
revive reviveOffers

### ISSUE THREAD

**Issue by erikdw** [mesos/storm#134]
[@brndnmtthws introduced the invocation of `_driver.reviveOffers()`](https://github.com/mesos/storm/blob/af8c49beac04b530c33c1401c829caaa8e368a35/src/main/storm/mesos/MesosNimbus.java#L322-L323) to allow the framework to get previously declined offers sent back to itself.

Then the call was was [inadvertently removed by @dsKarthick in this refactoring change](https://github.com/mesos/storm/commit/cdd7264f97457a9150df4a46591f2a5b691dfc0f).

We should consider reintroducing it.

Note that `_reviveOffers()` is called every 10 seconds, since the frequency of the nimbus-core calling `allSlotsAvailableForScheduling()` is driven by the [`nimbus.monitor.freq.secs` setting](https://github.com/apache/storm/blob/v0.9.6/conf/defaults.yaml#L48).  This is pretty often, and much less than the default ["filter seconds" of 120 seconds](https://github.com/mesos/storm/blob/da06e446fb750d8624280c39f3c0eb888a6a530b/storm/src/main/storm/mesos/MesosNimbus.java#L227).  I believe this means that with the default settings, we will never reach the 120 second timeout and the declined resources will be re-offered much more quickly.

**Comment by erikdw** [comment]
Note: discovered this issue while responding to #132 .

**Comment by erikdw** [comment]
@JessicaLHartog : I'm pretty sure this is obviated by the changes in PR #200 , so I'm going to assign this to you to move to its final disposition.

**Comment by JessicaLHartog** [comment]
You're right @erikdw, this is fixed in PR #200. Will close this issue once that's good to merge.

**Comment by erikdw** [comment]
Closing this per [@JessicaLHartog 's comments](https://github.com/mesos/storm/issues/134#issuecomment-321311251).

**Comment by erikdw** [comment]
v0.2.4+ has this fix. For v0.1.x (storm-0.x support) we haven't done a release yet.
