### ISSUE TITLE
Storm 0.10 Thrift port type bug - Outdated docker image

### ISSUE THREAD

**Issue by jaimelive** [mesos/storm#140]
A bug interpreting the thrift port as a long instead of an int has been fixed by storm as seen in https://issues.apache.org/jira/browse/STORM-1645
however the docker images at mesos/storm and mesosphere/storm are still outdated.

**Comment by erikdw** [comment]
@jaimelive : so you're pointing out that we should upgrade the storm version from 0.10.0 to 0.10.1 within the project.  Totally agreed!  I'll handle that.

**Comment by erikdw** [comment]
@jaimelive : phew, finally the `mesos-0.28.2` packages were available and the builds passed.  So the fixed packages and docker images for v0.1.3 are here:
* https://hub.docker.com/r/mesos/storm/tags/
* https://github.com/mesos/storm/releases
