### ISSUE TITLE
LocalFileServer does not resolve to fully qualified host

### ISSUE THREAD

**Issue by asanami** [mesos/storm#16]
The LocalFileServer.java file starts a web server for serving the storm.yaml file.  This resolves to host to its local hostname.  For our use-case we require the fully qualified hostname including its domain name:

```
private String getHost() throws Exception {
    final String envHost = System.getenv("MESOS_NIMBUS_HOST");
    if (envHost == null) {
      return InetAddress.getLocalHost().getHostName();
    } else {
      return envHost;
    }
  }
```

Can ``getHostName()`` be changed to ``getCanonicalHostName()``

**Comment by erikdw** [comment]
This was fixed in https://github.com/mesos/storm/pull/20
