### ISSUE TITLE
Failed to detect a master: Failed to parse data of unknown label 'json.info'

### ISSUE THREAD

**Issue by zhanghangchina** [mesos/storm#168]
I have a problem
please tell me how to solve the problem.
Thank you very much!
![1](https://cloud.githubusercontent.com/assets/20829283/17694514/c4005ffa-63d6-11e6-8de1-a2d3425a0df7.PNG)
![1](https://cloud.githubusercontent.com/assets/20829283/17694540/e51e11d2-63d6-11e6-9b30-0226aab964ac.PNG)
![2](https://cloud.githubusercontent.com/assets/20829283/17694547/f2bcb1c2-63d6-11e6-8585-a0dacc62a9a9.PNG)

**Comment by erikdw** [comment]
hey @zhanghangchina : sorry for the delay in response.  I'm actually on vacation right now.  But that issue you are seeing is an error from mesos itself, and thus is not related to [this project](mesos/storm):

```
Trying to get '/mesos/json.info_0000000152' in ZooKeeper
Failed to detect a master: Failed to parse data of unknown label 'json.info'
```

I would ensure your Mesos setup is correct.  e.g., with my setup I have 3 masters here and here's what my `/mesos` dir has in ZooKeeper:
```
[json.info_0000000229, log_replicas, json.info_0000000231, json.info_0000000225]
```

You may need to clean up the ZK nodes in `/mesos` and try again.

**Comment by erikdw** [comment]
Feel free to comment again, but I'm closing this issue as it's not a problem in this project.
