### ISSUE TITLE
How to deal with mesos master leader changes when you use storm < 1.0.0

### ISSUE THREAD

**Issue by salimane** [mesos/storm#169]
I came across a situation whereby if the mesos master leader is not the same as the node on which the storm nimbus is setup on, the storm ui/setup is borked.
Basically with storm < 1.0.0 cannot cope with multiple mesos masters and mesos master leader changes.
has anyone experienced this ?
cc @erikdw 
Thanks

**Comment by erikdw** [comment]
@salimane : can you tell me more about your setup & what exactly the storm ui being borked means?  We haven't had any problems like this, but we don't run the storm ui nor storm nimbus within the mesos cluster itself.  Only the supervisors & workers are run in our mesos cluster.

**Comment by salimane** [comment]
@erikdw sorry I was my mistake. there was a typo in the zookeepers url. closing this

**Comment by erikdw** [comment]
@salimane: ahh, thanks for clearing that up, and no worries.
