### ISSUE TITLE
bin/storm-mesos does not check exit status

### ISSUE THREAD

**Issue by asanami** [mesos/storm#17]
The storm-mesos wrapper in the bin directory ignores the exit status of storm.

**Comment by erikdw** [comment]
[Here is the version of storm-mesos](https://github.com/mesos/storm/blob/b007d54b1a7fad5044932798c1000149d14afd14/bin/storm-mesos) at the time of this bug report's creation.

And [here is the latest as of the time of my comment](https://github.com/mesos/storm/blob/faf35e577755da9ecd1f24da66e3f71002dbfe71/bin/storm-mesos)

**Comment by erikdw** [comment]
The wrapper script is still ignoring the exit status in the [latest incarnation](https://github.com/mesos/storm/blob/faf35e577755da9ecd1f24da66e3f71002dbfe71/bin/storm-mesos).  We can do `sys.exit()` around the `subprocess.call` invocation to use its return value as the exit code of the script.

**Comment by erikdw** [comment]
This will be fixed by merging the above change.
