### ISSUE TITLE
Storm 1.0.2 on Mesos 1.0.0

### ISSUE THREAD

**Issue by zhanghangchina** [mesos/storm#170]
What can I do to make storm 1.0.2 integrating into mesos 1.0.0?

**Comment by erikdw** [comment]
@zhanghangchina : 

* Regarding **storm 1.0.2**:  as discussed in #128, we don't have support in the `master` branch of this project for storm 1.0+.  I don't have time to work on that right now, maybe next month.

* Regarding **mesos 1.0.0**:  the project *may* work with mesos 1.0.0.  I'm not sure, I just built it with 1.0.0 from master, and the build completed.  But I'm not sure if it will run correctly.

Here's what I suggest you *try* to do:

1. First check if the project will work with mesos 1.0.0 and storm 0.9.6 (or 0.10.1):
   * build it using this command:  `STORM_RELEASE=0.9.6 MESOS_RELEASE=1.0.0 bin/build-release.sh`
   * then run it using your own setup somehow
2. Assuming it works, then you can either;
   * take my https://github.com/erikdw/storm-mesos/tree/1.0.0-WIP  branch that is referenced from #128 and build the project from that, but targeting mesos 1.0.0.
   * OR port my changes from that branch into the master on your own local repo and then build the project

**Comment by zhanghangchina** [comment]
I have verified the success of integratingstorm 0.10.0 into mesos 1.0.0.This is the right thing.Taking the liberty of asking, what time is it done?

**Comment by erikdw** [comment]
@zhanghangchina : I'm not sure what "this is the right thing" means. ;-)

I have a lot of work responsibilities other than the care & maintenance of this single project (which I've already spent a ton of time on this year to get it to the point that it's at).  So it's hard for me to estimate, I cannot commit to any particular date.  I hope to get time in October.  If you wanted to work on it that would be cool.  Otherwise you'll have to settle for #2 above.

**Comment by DarinJ** [comment]
@erikdw @zhanghangchina my group is considering the move to Storm-1.0.2, if so that'll force them to free me up enough to work on it.  That likely won't be until late October though. 

I'll certainly spare cycles to review and test a PR for this though @ ping me to ensure I pay attention.

**Comment by erikdw** [comment]
@DarinJ : thanks for the offer.  I may get time before that, I'll ping here if so to avoid duplicate work.

**Comment by erikdw** [comment]
@DarinJ : as [I noted in #128](https://github.com/mesos/storm/issues/128#issuecomment-257212832), I'm finally working on this.

**Comment by erikdw** [comment]
@zhanghangchina : complete, see [this comment](https://github.com/mesos/storm/issues/128#issuecomment-258646596).
