### ISSUE TITLE
How set the value of "worker.childopts: " for every Topology.

### ISSUE THREAD

**Issue by handmail** [mesos/storm#171]
I wanted to set the value of "worker.childopts: " for every Topology.
When storm not on mesos, I can do it in this way:
`Config conf = new Config();`
`conf.put(Config.TOPOLOGY_WORKER_CHILDOPTS, "-Xmx4068m");`

After storm on mesos,  above way is workable ?

**Comment by JessicaLHartog** [comment]
@handmail 
So there are two ways I can interpret your "for every Topology" statement, I'll explain both below:

- To set a _default_ of `worker.childopts` for _every topology_ modify [stom.yaml](https://github.com/mesos/storm/blob/master/storm.yaml#L14): 
  `worker.childopts: "-Xmx4068m"`
  Note that if you try to set this in your topology, it will show up in the topology config in the Storm UI, but it will *not* be respected.

- For every topology to control this setting on their own, it works similarly to Storm as you pointed out above, except that you push in `topology.worker.childopts` as the configuration option:
  `conf.put("topology.worker.childopts", "-Xmx4068m");`


In *both* of these cases, modifying this value can have negative impacts if you don't also change the default container allocation for memory.
- To modify the default requested memory for _every topology_ modify [storm.yaml](https://github.com/mesos/storm/blob/master/storm.yaml#L13):
  `topology.mesos.worker.mem.mb: 5085`

- For every topology to control this setting on their own it works similarly to Storm as above, but this time the option is `topology.mesos.worker.mem.mb` as the configuration option:
  `conf.put("topology.mesos.worker.mem.mb", 5085);`

Note that in both cases I've increased the headroom by 25% from your example, as per the [documentation's suggestion](https://github.com/mesos/storm/blob/f91143f4e34724ffc4b95f1b80039f7c2e432367/README.md#resource-configuration). Without making this modification as well, the topology will probably crash, so you need to make sure you have a request for ~5000MB of memory for the containers if you change the childopts to the value you proposed.

**Comment by JessicaLHartog** [comment]
Marking this issue closed. Feel free to re-open if you still have questions.
