### ISSUE TITLE
Download links for storm-mesos releases

### ISSUE THREAD

**Issue by asanami** [mesos/storm#18]
Can you please provide clarification on where to pick up releases for storm-mesos.  The storm.yaml file references download links to:

http://downloads.mesosphere.io/storm/storm-mesos-0.9.0.1.tgz

I cannot find releases from the official mesosphere web page, and more specifically looking for the storm-mesos-0.9.2 release.

Thanks

**Comment by erikdw** [comment]
The plan is to have these releases available for download from within the github project page.

But before that we need some version scheme.  i.e., the framework has enough changes that simply referring to the storm version is insufficient.   We should have a version for the framework itself, and also reference the storm version that is included within the package.  e.g., like how kafka packages reference the scala version they are built with:
* `kafka_2.9.1-0.8.2.2` == Kafka Version `0.8.2.2` built with Scala version `2.9.1`

**Comment by erikdw** [comment]
The version naming scheme is being discussed in #76

**Comment by erikdw** [comment]
Per #76, we've agreed upon a version naming scheme, so when PR #77 is complete we can proceed publish our first "official" releases on this github project page.

### How to upload releases
* https://github.com/blog/1547-release-your-software
* https://help.github.com/articles/about-releases/
  * notably, releases are allowed to be up to 2GB in size, so we're good with the ~26MB releases we currently have

### Building releases
I'm not sure of the full process yet, but here's a stab at it:

#### dreary present: super manual process
1. manually rev the version
2. `bin/build-release.sh`
3. gci -m "release version X.Y.Z"; git tag vX.Y.Z; git push; git push --tags
4. Upload the tarball to this [project's releases view](https://github.com/mesos/storm/releases)

#### copacetic short-term improvement: less manual process with maven assistance
Then we can move to leverage maven for automating some of the painful manual steps in there:
1. run the `maven assembly` plugin (or some other one) for running `bin/build-release.sh`
2. use the `maven release` plugin to manage the versions updating and tagging
3. we still manually upload the tarball to this [project's releases view](https://github.com/mesos/storm/releases)

#### glorious future: full automation

Ideally we'd leverage travis-ci.org.  See #83.

**Comment by erikdw** [comment]
Now that @DarinJ's #77 change has landed we have the basis for creating actual builds.  I'll spend some time building a few variations and uploading them to the github project's releases page.

**Comment by erikdw** [comment]
Awesomely we have reached the "glorious future" already with @salimane's contribution in #117.

We still should enhance the setup to allow use of the `mvn release` plugin so that there are less possibilities for manual screw-ups.  See #127.
