### ISSUE TITLE
mesos/storm docker images: Upgrading to Mesos v1.1.0

### ISSUE THREAD

**Issue by chjhaijiang** [mesos/storm#181]
I see there are serveral docker images in docker hub, but didn't get a document how to upgrade and make it work with mesos 1.1.0. 

https://hub.docker.com/r/mesos/storm/tags/

**Comment by chjhaijiang** [comment]
Is there any dockerfile that was used? Or any tips about how to upgarde https://github.com/mesos/storm/blob/master/Dockerfile?

**Comment by erikdw** [comment]
@chjhaijiang : we haven't updated for the new Mesos version yet.  We can do that pretty easily if it works to build (it just requires modifying [.travis.yml](https://github.com/mesos/storm/blob/master/.travis.yml) in this repo to have some extra mesos versions, or changing the latest mesos version to be 1.1.0 from 1.0.2).   If you wanna test yourself locally you can follow the [instructions in the repo's README](https://github.com/mesos/storm/blob/68432a15103cdf00b137ef740730c2e7b7682547/README.md#docker-images-building).

**Comment by erikdw** [comment]
When [this Travis-CI build](https://travis-ci.org/mesos/storm/builds/184134391) completes, the artifacts will be available in DockerHub as well as on the GitHub releases page for this repo.
