### ISSUE TITLE
Spout is not reading/emitting data in storm cluster mode

### ISSUE THREAD

**Issue by geekyminhaj** [mesos/storm#197]
I am using apache storm 1.0.0 both in local as well as cluster mode. For the spout, I am reading the data from kafka topic (I am using kafka 2.11-0.8.2.1). Spout is reading the data from kafka topic and also emitting the data when I am using storm in local mode but the storm spout is not emitting any data when I am running storm in cluster mode.

**My topology implementation for reading kafka data is as follow:**
 
brokerHosts = new ZkHosts(kafkaZookeeper);
SpoutConfig kafkaConfig = new SpoutConfig(brokerHosts, kafkaTopicIn, "", "storm");
kafkaConfig.scheme = new SchemeAsMultiScheme(new StringScheme());
TopologyBuilder builder = new TopologyBuilder();
builder.setSpout("spout", new KafkaSpout(kafkaConfig), 2);

**My storm configuration file:**
storm.zookeeper.servers:
     - "localhost"
storm.zookeeper.port: 2181
nimbus.seeds: ["localhost"]

storm.local.dir: "/tmp/storm"

I am also not getting any error while submitting Storm topology in cluster mode.

Any idea why topology spout is not emitting any data in cluster mode ??
Any help would be greatly appreciated.

**Comment by erikdw** [comment]
@geekyminhaj : is there any reason you believe this is specific to the storm-on-mesos project?  It seems like this is a general Storm usage question, which would be more appropriately posed on the storm user mailing list:
* https://storm.apache.org/getting-help.html

FWIW, I don't see anything obviously wrong, you'll *definitely* need to dig into this more on your own and provide more information before asking a question of the storm user list.
