### ISSUE TITLE
Wrong storm.yaml downloaded from nimbus

### ISSUE THREAD

**Issue by maverick2202** [mesos/storm#24]
I am using http://downloads.mesosphere.io/storm/storm-mesos-0.9.2-incubating.tgz. Issue is that nimbus has the it under conf/storm.yaml . However, when worker starts to fetch it is looking into storm.yaml (not inside conf). 

This results in download error and topology doesn't start. This worked fine with storm-mesos-0.9. Any help will be appreciated why worker looking into wrong directory in 0.9.2 version.

**Comment by chengweiv5** [comment]
that should not true, it should look into conf/storm.yaml, however, the conf/storm.yaml in http://downloads.mesosphere.io/storm/storm-mesos-0.9.2-incubating.tgz by default point to 

> mesos.executor.uri: "http://downloads.mesosphere.io/storm/storm-mesos-0.9.0.1.tgz"

And seems there isn't such file, you may configure it to a correct url.

**Comment by ondrej-smola** [comment]
Same bug:

```
I0116 07:43:40.820832 20964 fetcher.cpp:76] Fetching URI 'file:///opt/storm-mesos-0.9.2.tgz'
I0116 07:43:40.820988 20964 fetcher.cpp:179] Copying resource from '/opt/storm-mesos-0.9.2.tgz' to '/tmp/mesos/slaves/20150116-053835-171485376-5050-17555-S1/frameworks/20150116-053835-171485376-5050-17555-0002/executors/myTopo2-1-1421394220/runs/41b7ff3d-0df3-468b-8835-225923db89b1'
I0116 07:43:41.079344 20964 fetcher.cpp:64] Extracted resource '/tmp/mesos/slaves/20150116-053835-171485376-5050-17555-S1/frameworks/20150116-053835-171485376-5050-17555-0002/executors/myTopo2-1-1421394220/runs/41b7ff3d-0df3-468b-8835-225923db89b1/storm-mesos-0.9.2.tgz' into '/tmp/mesos/slaves/20150116-053835-171485376-5050-17555-S1/frameworks/20150116-053835-171485376-5050-17555-0002/executors/myTopo2-1-1421394220/runs/41b7ff3d-0df3-468b-8835-225923db89b1'
I0116 07:43:41.083520 20964 fetcher.cpp:76] Fetching URI 'http://master1:33858/storm.yaml'
I0116 07:43:41.083583 20964 fetcher.cpp:126] Downloading 'http://master1:33858/storm.yaml' to '/tmp/mesos/slaves/20150116-053835-171485376-5050-17555-S1/frameworks/20150116-053835-171485376-5050-17555-0002/executors/myTopo2-1-1421394220/runs/41b7ff3d-0df3-468b-8835-225923db89b1/storm.yaml'
E0116 07:43:41.145236 20964 fetcher.cpp:132] Error downloading resource, received HTTP/FTP return code 404
Failed to fetch: http://master1:33858/storm.yaml
Failed to synchronize with slave (it's probably exited)
```
http://master1:33858/conf/storm.yaml  resolves ok

**Comment by viktortnk** [comment]
The issue should be fixed since that PR got merged

https://github.com/mesos/storm/pull/10/files

**Comment by pradeepchhetri** [comment]
@viktortnk How can i get the version of `mesos-storm` with this fix ?

**Comment by viktortnk** [comment]
I believe the best is to build it yourself. Check README for instructions. You might easily host it for free on a service like Bintray

Or for quick test I can suggest https://bintray.com/artifact/download/whisklabs/generic/storm-mesos-0.9.3-1.tgz (it is not the latest though)

**Comment by pradeepchhetri** [comment]
@viktortnk Thank you Viktor. I tried using the link you sent. Do you know what should be the minimum resource available on a mesos-slave machine for any topology to start executing. I am running on t2.small instance (1CPU, 1000MB) as mesos-slave and i am seeing `Number of available slots: 0` in nimbus logs.

**Comment by viktortnk** [comment]
@pradeepchhetri It will not show you slots available. Pool of resources is managed by Mesos.

Check these params in the end of the README

`topology.mesos.worker.mem.mb`
`topology.mesos.executor.mem.mb`

worker node should at least have another memory to fit 1 worker + 1 executor for topology.

**Comment by pradeepchhetri** [comment]
@viktortnk Work perfectly !! Thank you Viktor.

**Comment by pradeepchhetri** [comment]
@viktortnk I tried changing values of  `topology.mesos.worker.mem.mb` and `topology.mesos.executor.mem.mb` variables in `storm.yml` but somehow it is not picking. Otherwise everything works fine.

**Comment by erikdw** [comment]
@pradeepchhetri : did you get that working?  Those values are per-topology, so you set them in the topology's `backtype.storm.Config` object that is passed to `StormSubmitter.submitTopology`.
