### ISSUE TITLE
Configurable worker CPU/mem per topology.

### ISSUE THREAD

**Issue by evilezh** [mesos/storm#26]
I know - this makes harder to determine available slots, but would be very useful in terms of executing topology with required resources.
Probably that means that by default available slots is 0 and new slot is created at time topology is submitted to storm cluster. Then determine required resources and allocate them if possible, or allocate when it becomes available.

**Comment by brndnmtthws** [comment]
You can in fact already do this, FYI. Just set `topology.mesos.worker.cpu`, `topology.mesos.worker.mem.mb`, and `worker.childopts` appropriately within the topology.

**Comment by evilezh** [comment]
Ok - where does it happens ? Here is some code MesosNimbus.java:
for (String id : topologiesMissingAssignments) {
   TopologyDetails details = topologies.getById(id);
   double tcpu = MesosCommon.topologyWorkerCpu(_conf, details);
   double tmem = MesosCommon.topologyWorkerMem(_conf, details);
   if (cpu == null || tcpu > cpu) {
      cpu = tcpu;
   }
   if (mem == null || tmem > mem) {
      mem = tmem;
   }
}
I guess this calculates mem,cpu resources, which is determined by MesosCommon.topologyWorkerCpu(_conf, details).
_conf is nimbus configuration:
 @Override
public void prepare(Map conf, String localDir) {
try {
_conf = conf; .......................

At which point does it take care about topology variables ?


Here is how I understand and my idea :)
this call returns available slots.
public Collection<WorkerSlot> allSlotsAvailableForScheduling(Collection<SupervisorDetails> existingSupervisors, Topologies topologies, Set<String> topologiesMissingAssignments).
Then we query mesos for resources and return slots.
Now imagine .. I've 2 topologies which needs scheduling .. for one I want 4 cpu/2GB per worker and another 1cpu/500Mb per worker.
Within this call we will return worker slots for none for one or for both topologies.

Maybe extend WorkerSlot and already tag WorkerSlot with topologyID for which topology that WorkerSlot is. before .schedule call there is other calls which will read allSlotsAvailableForScheduling and that way we can bypass our extended WorkerSlots where assigments will be made already and our scheduler will just do assigments as we like :)


Fix me if I'm wrong,  I just spend hour trying to understand how it works, i can miss many things.
Also I think without implementing storm Scheduler it will not work all properly.

**Comment by brndnmtthws** [comment]
See the code in `MesosCommon.java`, here: https://github.com/mesos/storm/blob/master/src/storm/mesos/MesosCommon.java#L57-L106

**Comment by evilezh** [comment]
These are static methods and compute from Map you provide. 
And provided Map is nimbus configuration.
Probably we are on different wave.

Give me example you you will start one topology with 4cpu, 2gb per worker and another topology with 2cpu and 4gb per worker. How you will configure it within one cluster with current code.

**Comment by brndnmtthws** [comment]
The topology details are extracted here: https://github.com/mesos/storm/blob/master/src/storm/mesos/MesosNimbus.java#L349

**Comment by evilezh** [comment]
You are right, it is merging, shame on me :).

Maybe I did think so, because i focused on  this:
 for (String id : topologiesMissingAssignments) {
     TopologyDetails details = topologies.getById(id);
     double tcpu = MesosCommon.topologyWorkerCpu(_conf, details);
     double tmem = MesosCommon.topologyWorkerMem(_conf, details);
     if (cpu == null || tcpu > cpu) {
        cpu = tcpu;
}
   if (mem == null || tmem > mem) {
      mem = tmem;
}
}
On exit you get largest value ? largest mem across topologies and largest cpu.
Then using largest value you calculate slots: 
List<WorkerSlot> allSlots = new ArrayList<WorkerSlot>();
if (cpu != null && mem != null) {
    synchronized (OFFERS_LOCK) {
        for (Offer offer : _offers.newestValues()) {
           allSlots.addAll(toSlots(offer, cpu, mem));
        }
    }
}
Is it right ?
