### ISSUE TITLE
Is there a way to rebalance workers ?

### ISSUE THREAD

**Issue by maverick2202** [mesos/storm#27]
In storm, I could rebalance number of workers as well as executor to increase parallelism without any downtime. How can i do the same in storm mesos ?

e.g. i start topology in storm mesos with #cpu, #mem and num.worker. How do i increase cpu or mem or num.woker without any bringing down the topology ?

I could do following in storm.

http://storm.apache.org/documentation/Understanding-the-parallelism-of-a-Storm-topology.html
$ storm rebalance mytopology -n 5 -e blue-spout=3 -e yellow-bolt=10

**Comment by chengweiv5** [comment]
did you give it a try?

**Comment by maverick2202** [comment]
What should i try ?

**Comment by brndnmtthws** [comment]
It should work the same as with non-Mesos Storm.

**Comment by dsKarthick** [comment]
@brndnmtthws +1

**Comment by dsKarthick** [comment]
@erikdw @tnachen this issued should be closed?

**Comment by erikdw** [comment]
Yeah, there is nothing storm-on-mesos specific here.  Closing.
