### ISSUE TITLE
Storm Authentication?

### ISSUE THREAD

**Issue by pdread100** [mesos/storm#35]
Is Storm authentication being worked? Plans? Ideas?

**Comment by pdread100** [comment]
Some one off line answered some of my question, that is mesos storm should use the mesos authentication framework. So I will add this if no one else has or is doing so.

**Comment by tnachen** [comment]
Please go ahead and help add framework authentication (principal, secret, etc) to this framework.

**Comment by erikdw** [comment]
This has already been fixed by #37
