### ISSUE TITLE
Upgrade to storm 0.9.4

### ISSUE THREAD

**Issue by pdread100** [mesos/storm#47]
Are there any known issues with upgrading to the newer storm?

**Comment by erikdw** [comment]
Nope, storm 0.9.4 works fine, as does storm 0.9.5.

**Comment by adam-mesos** [comment]
How about Storm 0.10.0? ;)

**Comment by erikdw** [comment]
Now... that's a bigger question. :)   There have been a ton of changes in storm 0.10 (not yet released).  I have it on my roadmap to investigate 0.10 in the next month or so.

**Comment by erikdw** [comment]
Storm 0.9.6 is now the version in this project as of #65 by @brndnmtthws , so I consider this fixed.

Storm 0.10 has been released, but is a much bigger change.  I haven't tested with it at all yet.
