### ISSUE TITLE
Support for storm-0.10.0

### ISSUE THREAD

**Issue by DarinJ** [mesos/storm#68]
Storm 0.10.0 changed a few things that break storm on mesos.  In particular:
- LocalState.get now returns a TBase object (thrift related) instead of String.
- bin/storm is now a bash script instead of python
- snakeyaml is no longer in the classpath
- commons-lang upgraded to common-lang3 which effects imports

I spent a little time correcting these, and have a really rough working version [here](https://github.com/darinj/storm/tree/0.10.0).  I'll probably clean it up next week as I need it, if there's interest I'll submit a PR.  This does break storm 0.9.X though so it may be good to write a shim or place on a separate branch/tag.

**Comment by erikdw** [comment]
@DarinJ : thanks for the research and prototype.  I haven't looked at the issues with storm-0.10.0 yet, but definitely wanna keep storm-0.9.x compatibility for now.   Not sure how hard a "shim" would be to write, but I suppose we could use maven profiles to separate out inclusion of some code / dependencies.

**Comment by salimane** [comment]
@erikdw @DarinJ we can use tag to deal with the compatibility issue

**Comment by erikdw** [comment]
@salimane : can you please elaborate on how using git tags would help deal with the issue?

i.e., we cannot just create a "storm-0.9.6" tag and freeze the code in its current form for when people run storm-0.9.6.  We have more changes to be made to the framework.  

A separate git branch could work, but requires double the work.   Ideally we would have a maven profile and/or some sort of bridge class.

**Comment by DarinJ** [comment]
@erikdw @salimane I think a separate branch is way too much work and it almost always ends up breaking something.  I've looked at the effort to do profiles for this and it's pretty trivial, just gotta find time to do it.  I hope to have something next week (maybe the week after).

To give you an idea of my plan:
- Have two storm-local-state-0.XX maven subprojects. They will contain a class implementing an interface wrapping `LocalState` to expose `get`, `put` and `remove` and a class which exposes the proper command line for the executor/supervisor. The storm-mesos project will use the correct subproject based off profile.  This solves 1 & 2. 
- Add a dependency for snakeyaml in the 0.10 profile, solving 3.
- Replace `StringUtils.isNotEmpty` from commons-lang with `!Strings.isNullorEmpty` from guava and remove the commons.lang import. This fixes 4. 

Open to suggestions.  Will also need to mod the build.sh script haven't thought that though yet.

**Comment by erikdw** [comment]
@DarinJ : that sounds like a solid plan to me!  Yes, time is always the hardest thing to come by. :)

**Comment by DarinJ** [comment]
@erikdw I found time! It's still a bit rough in terms of comments, headers, tests, and docs, but it runs the exclamation topology with storm 0.9.3, 0.9.6 and 0.10.0, using RELEASE=0.X.X bin/build-release.sh.  Probably a good time to get some feedback.  You OK with a WIP PR?  If so I'll submit later today, I already squashed my commits and rebased but expect I'll be making a few more commits before I'll want to merge.

Also, I think it may be good to break the version consistency (it's irrelevent with the RELEASE set anyway) with storm and instead have maven put a classifier tag related to storm release version on the artifact.  Thoughts?

**Comment by erikdw** [comment]
@DarinJ : 

1. Yup, a WIP PR would be great.
2. Totally agree that the versions being tied to the storm version is just wrong.  I'm not familiar with classifier tags, but from what you're saying it sounds good, though we *may* also want to have the storm (and mesos) versions stuffed into the version of the artifact, a la how kafka artifacts have the scala version shoved into 'em, as I [mentioned here](https://github.com/mesos/storm/issues/18#issuecomment-157561772).  Thoughts on that?

**Comment by erikdw** [comment]
Thanks @DarinJ for fixing this!
