### ISSUE TITLE
Dockerized workers having issues starting container

### ISSUE THREAD

**Issue by echinthaka** [mesos/storm#69]
I have been trying to get the dockerized workers working but seems like the workers are not properly starting on mesos. 

Here[1] is my storm.yaml. I'm getting this[2] error. Seems like `MESOS_NATIVE_JAVA_LIBRARY` is not getting passed into the [place](https://github.com/mesos/storm/blob/a1e79bb257d60ad5ccdb8f8d9c70daf6552eab85/src/main/storm/mesos/MesosNimbus.java#L801) thats creating the docker jobs. Can someone please help?

[1]
```
mesos.master.url: "zk://my-zk-1.example.com:2181/mesos"                                                
storm.zookeeper.servers:                                                                                               
  - my-zk-1.example.com                                                                              
                                                                                                                       
nimbus.host: "my-nimbus.example.com"                                                                 
# -----------------------------------------------------------                                                          
       
# Worker resources                                                                                       
topology.mesos.worker.cpu: 1.0                                                                           
# Worker heap with 20% overhead                                                                          
topology.mesos.worker.mem.mb: 1200                                                                       
worker.childopts: "-Xmx1000m"                                                                            
                                                                                                         
# Supervisor resources                                                                                   
topology.mesos.executor.cpu: 0.1                                                                         
topology.mesos.executor.mem.mb: 500 # Supervisor memory, with 20% overhead                               
supervisor.childopts: "-Xmx256m"                                                                         
                                                                                                         
# The default behavior is to launch the logviewer unless autostart is false.                             
# If you enable the logviewer, you'll need to add memory overhead to the                                 
# executor for the logviewer.                                                                            
logviewer.port: 8000                                                                                     
logviewer.childopts: "-Xmx128m"                                                                          
logviewer.cleanup.age.mins: 10080                                                                        
logviewer.appender.name: "A1"                                                                            
supervisor.autostart.logviewer: true                                                                     
                                                                                                         
mesos.container.docker.image: mesosphere/storm                           
                                                                                                         
storm.messaging.transport: "backtype.storm.messaging.netty.Context"                                      
                                                                                                         
storm.local.dir: "storm-local"                                                                           
                                                                                                         
# role must be one of the mesos-master's roles defined in the --roles flag                               
#                                                                                                        
mesos.framework.role: "*"                                                                                
mesos.framework.checkpoint: true                                                                         
mesos.framework.name: "Storm"                                                                            
                                                                       
```

[2]
```
java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: null
	at java.lang.Runtime.load0(Runtime.java:792) ~[na:1.7.0_85]
	at java.lang.System.load(System.java:1062) ~[na:1.7.0_85]
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159) ~[storm-0.9.6.jar:na]
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:188) ~[storm-0.9.6.jar:na]
	at org.apache.mesos.MesosExecutorDriver.<clinit>(MesosExecutorDriver.java:52) ~[storm-0.9.6.jar:na]
	at storm.mesos.MesosSupervisor.prepare(MesosSupervisor.java:67) [storm-0.9.6.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$exec_fn__1104__auto____5115.invoke(supervisor.clj:407) ~[storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.AFn.applyToHelper(AFn.java:167) ~[clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) ~[clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$mk_supervisor__5140.doInvoke(supervisor.clj:405) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:630) [storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.9.6.jar:0.9.6]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:50) [storm-0.9.6.jar:na]
2015-11-24T07:10:05.758+0000 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$mk_supervisor__5140.doInvoke(supervisor.clj:405) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:630) [storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.9.6.jar:0.9.6]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:50) [storm-0.9.6.jar:na]
```

**Comment by erikdw** [comment]
@echinthaka : are you experiencing this issue with the latest commits on master?  Did this work before the big commit in #65?  I haven't tried the Docker stuff in this project for awhile, but had it working prior to that big commit, and I don't think I did anything with MESOS_NATIVE_JAVA_LIBRARY.

**Comment by echinthaka** [comment]
@erikdw I got the latest checkout from the master and did this. Didn't check it prior to #65 . I think I need to have #65 assuming it has dockerized storm workers/supervisors.
Until this gets resolved thinking of manually hacking the code in `MesosNimbus` class to hard code `MESOS_NATIVE_JAVA_LIBRARY` to `/usr/lib/libmesos.so`.

**Comment by erikdw** [comment]
pre-#65 also works with docker, you have to run `bin/build-release.sh` and *then* `bin/build-release.sh dockerImage`.

**Comment by echinthaka** [comment]
thanks @erikdw . In that case, I will get rebase to pre#65. BTW, what exactly is #65 adding then?

I see the following two on #65's commit message and hence thought its needed
```
Improved Docker support, added support for running Storm inside containers. This also introduces the mesos.container.docker.image config param
Improved port handling, especially with regard to logviewer
```

**Comment by erikdw** [comment]
@echinthaka : #65 adds a *ton* of stuff. :)   *Better* docker support, a marathon setup, support for reserved resources in mesos, etc.  Please consult the Description of that PR for more info.

Also, unless you have changes in place you don't need to "git rebase", you can just "git checkout".  Also, I'm not asking that you only run on the old version, I'm simply asking if you can reproduce the problem on a version where I previously was unable to.  I'll have time later today to work on this stuff, so hopefully I'll know how to workaround your problem, assuming I can reproduce it.

**Comment by erikdw** [comment]
@echinthaka : FYI, I *just* experienced this problem with the vagrant setup in this project, without using docker.  I'm working on improving the vagrant setup and this problem just seems to have randomly come up.  i.e., following the same steps I've been doing thru the day, I've somehow managed to get into a state where the MesosSupervisor fails to launch due to the same error you pasted above.   So it seems this problem might be somewhat random and also not specific to docker.

**Comment by erikdw** [comment]
:hourglass_flowing_sand: :no_mouth:   sooo.... I encountered your problem simply because I screwed up while moving some code around (I had `git stash`ed my storm.yaml changes to use the non-docker setup).

Looking at [the code you pointed at](https://github.com/mesos/storm/blob/a1e79bb257d60ad5ccdb8f8d9c70daf6552eab85/src/main/storm/mesos/MesosNimbus.java#L793-L801), we can see that @brndnmtthws has put in a requirement that you have `MESOS_NATIVE_JAVA_LIBRARY` set explicitly in the environment of your MesosNimbus process, which is not the case for me, and seemingly not for you either.  This results in the MesosSupervisor / executor process having the following environment variables values as it launches [1]
* `MESOS_NATIVE_JAVA_LIBRARY=null`
* `MESOS_NATIVE_LIBRARY=/usr/lib/libmesos-0.25.0.so`

The `MESOS_NATIVE_JAVA_LIBRARY` being `null` explains the behavior we are seeing.
So either:
1. you'll need to set that environment variable when starting the MesosNimbus yourself.  
2. Or maybe we should instead change the MesosNimbus.java code to use a config option for setting this value.

(Notably, in the non-docker situation the env variable is set just fine for the executor process for me, so I'm not sure what the DCOS bug is that Brenden is referencing.)

[1] Since the processes die quickly, I had to craft the following bash loop to catch the nascent processes and examine their environment variables:
```
while true ; do for p in /proc/[0-9]*; do sudo sh -c "strings $p/environ | grep MESOS && cat $p/cmdline ; strings $p/environ | grep MESOS" ; done; done;
```

**Comment by brndnmtthws** [comment]
I'm not sure if the issue is actually DCOS specific, but for whatever reason the Docker env is not being passed to the executor:

https://github.com/mesos/storm/blob/master/Dockerfile#L15

So I added the following to make sure it gets set:

https://github.com/mesos/storm/blob/master/src/main/storm/mesos/MesosNimbus.java#L793-L801

Without this, the executor fails to start because it can't find libmesos. But this _only_ happens with Docker.

**Comment by echinthaka** [comment]
@erikdw actually we are setting `MESOS_NATIVE_JAVA_LIBRARY` . Check here in the Dockerfile: https://github.com/mesos/storm/blob/master/Dockerfile#L15. Hence, I think, as @brndnmtthws mentioned this might be an issue with Mesos. Note that I'm NOT using DCOS but Mesos. Even with the fix @brndnmtthws had put in `MesosNimbus.java`, I'm still seeing that issue. 

Wondering what a good workaround would be. Can we read this from `storm.yaml`?

**Comment by brndnmtthws** [comment]
As an alternative, we could put something into `bin/storm-mesos` (which is a Python wrapper script) to set the env var correctly, if it's not set. I'm concerned it might break things for others, however. Thoughts?

**Comment by erikdw** [comment]
Might as well read it from the config, a la other settings, no?

**Comment by erikdw** [comment]
And @echinthaka: how are you deploying the MesosNimbus?  Are you running it from the Dockerfile?

As I mentioned earlier, it seems like if the MesosNimbus *does* have the `MESOS_NATIVE_JAVA_LIBRARY` variable in its environment, then it will be correctly propagated to the executor process.  Are you sure it's set in the MesosNimbus for you?

**Comment by echinthaka** [comment]
@erikdw yes I'm running it through the docker image. 

When this was running within Docker, I got into that container and checked the env variable. And it is set correctly. So, for some reason it is not getting passed or read in `MesosNimbus` (this is similar to what @brndnmtthws mentioned related to DCOS as well I think)

**Comment by erikdw** [comment]
I don't understand then -- if the environment of the MesosNimbus process has the variable in its environ (are you sure it's `MESOS_NATIVE_JAVA_LIBRARY` and not the `MESOS_NATIVE_LIBRARY` one?) then it would be set in the executor, right?

**Comment by erikdw** [comment]
Closing for now, I have been unable to reproduce this issue and haven't heard back from the reporter.
