### ISSUE TITLE
bin/build-release.sh dockerImage should be passed environment variables

### ISSUE THREAD

**Issue by drewrobb** [mesos/storm#90]
When I run `STORM_RELEASE=0.10.0 bin/build-release.sh dockerImage` the docker build command that gets run ignores my `STORM_RELEASE` setting when it runs.

**Comment by erikdw** [comment]
Hmmph, yup. The `bin/build-release.sh dockerImage` isn't modifying the Dockerfile, and I'm not familiar enough with Docker to know what the "right" way to do that is.  i.e., is there some way to pass the fields when we invoke `docker build` such that we would set STORM_RELEASE and MESOS_RELEASE for the `bin/build-release.sh` invocation inside of the Dockerfile?

**Comment by erikdw** [comment]
The workaround is to modify the Dockerfile by hand to have the STORM_RELEASE & MESOS_RELEASE environment variables set appropriately in the bin/build-release.sh line.  Might have to set them using an `ENV` Dockerfile command -- again, not something I've ever tried before.

**Comment by erikdw** [comment]
Found this docker thread, seems that passing env variables to the Dockerfile is unsupported and would represent an anti-pattern.  That being said, I'm not sure what the *right* way to do it is.  Maybe have the `bin/build-release.sh` do a `sed` to replace fields in the Dockerfile before building?
* https://github.com/docker/docker/issues/6822

**Comment by drewrobb** [comment]
I think I might have a solution using docker `--build-args` feature. I'll maybe have a PR later today...

**Comment by erikdw** [comment]
oh, cool, thanks @drewrobb!
